#!/bin/bash
set -e # stop execution if a command or pipeline has an error
set -x # print statements as they're being executed

# Convert the Jupyter notebook to a Python script
docker run --volume $PWD:/src --interactive --tty cog-github-avatars jupyter nbconvert --to script notebook_v2.ipynb

# Build the Cog Docker image
cog build